name: Terraform Deployment 

on:
 push: 
  branches: 
    - main 


    # Declare the running agent - Github syntak we call it job , install - Terraform 
jobs:
  terraform-ci: 
    runs-on: ubuntu-latest 

    steps:
    # setup 

    # git clone /git checkout 
    - name: Checkout repository 
      uses: actions/checkout@v2 

    #aws configure 
    - name: Configure AWS Credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # or hardcode us-east-1

    #install terraform 
    - name: Set up Terraform 
      uses: hashicorp/setup-terraform@v1

    #teraform init 
    - name: Initialize Terraform 
      run: terrsform init 
    # terraform   
    - name: Terraform Validate
      run: terraform validate -no-color
    # terraform   
    - name: Terraform plan
      run: terraform plan
    
  # install 

# Decide when to run CI/CD pipeline 
# Git push and outload our code into repository 
#  Create AWS login configure the IAM secret key credential configure 
# Git clone / git_checkout 
# Terrafrom init 
# Terraform plan

# 